import { readFileSync } from "fs";
import { EnrichedRepo } from "../schema/github.js";
import { createMarkdownRow } from "./row.js";

const TABLE_HEADER = [
  "| Repository | Owner | Stars | Forks | Issues | Size | Topics | License | Created | Updated | Description |",
  "| ---------- | ----- | ----: | ----: | -----: | ---: | ------ | ------- | ------- | ------- | ----------- |",
];

const BACK_TO_INDEX_FOOTER = [
  "",
  "---",
  "",
  "[![Back to Index](https://img.shields.io/badge/←_Back_to_Index-000?style=flat-square&logo=github)](./README.md)",
];

export function formatSection(title: string, repos: EnrichedRepo[]): string {
  const header = [`## ${title}`, "", ...TABLE_HEADER];
  const rows = repos.map(createMarkdownRow);
  return [...header, ...rows].join("\n");
}

export function createMarkdown(repos: EnrichedRepo[]): string {
  const header = [
    "# Awesome MCP Repos",
    "",
    `Generated: ${new Date().toISOString().split("T")[0]}`,
    "",
    `Total: ${repos.length} repositories`,
    "",
    ...TABLE_HEADER,
  ];

  const rows = repos.map(createMarkdownRow);

  return [...header, ...rows, ...BACK_TO_INDEX_FOOTER].join("\n");
}

function buildReadmeIndexBlock(repoCount: number): string {
  const updatedDate = new Date().toISOString().split("T")[0];

  const lines = [
    `![Total Repos](https://img.shields.io/badge/Total_Repos-${repoCount}-blue?style=for-the-badge) ![Last Updated](https://img.shields.io/badge/Updated-${updatedDate}-green?style=for-the-badge)`,
    "",
    "[![⭐ Top Starred](https://img.shields.io/badge/⭐_Top_Starred-FFD700?style=for-the-badge&logo=github)](./TOP-STARRED.md) [![🍴 Top Forked](https://img.shields.io/badge/🍴_Top_Forked-5B2DAD?style=for-the-badge&logo=github)](./TOP-FORKED.md) [![👀 Top Watched](https://img.shields.io/badge/👀_Top_Watched-8E24AA?style=for-the-badge&logo=github)](./TOP-SUBSCRIBED.md)",
    "",
    "[![🗂️ Top Issues](https://img.shields.io/badge/🗂️_Top_Issues-E64727?style=for-the-badge&logo=github)](./TOP-ISSUES.md) [![💾 Top Largest](https://img.shields.io/badge/💾_Top_Largest-737894?style=for-the-badge&logo=github)](./TOP-LARGEST.md) [![🔥 Activity](https://img.shields.io/badge/🔥_Activity-FF4500?style=for-the-badge&logo=github)](./ACTIVITY.md)",
    "",
    "[![📋 All Repos](https://img.shields.io/badge/📋_All_Repos-000000?style=for-the-badge&logo=github&logoColor=white)](./AWESOME-MCP-REPOS.md)",
  ];

  return lines.join("\n");
}

export function updateReadmeWithIndex(
  readmePath: string,
  repoCount: number,
): string {
  const existingReadme = readFileSync(readmePath, "utf-8");
  const startMarker =
    "<!-- AUTO-GENERATED BY find-awesome-mcp-servers SCRIPT -->";
  const endMarker = "<!-- END AUTO-GENERATED -->";

  const startIndex = existingReadme.indexOf(startMarker);
  const endIndex = existingReadme.indexOf(endMarker);

  if (startIndex === -1 || endIndex === -1) {
    throw new Error("Could not find AUTO-GENERATED markers in README.md");
  }

  const before = existingReadme.slice(0, startIndex + startMarker.length);
  const after = existingReadme.slice(endIndex);
  const indexBlock = buildReadmeIndexBlock(repoCount);

  return `${before}\n\n${indexBlock}\n\n${after}`;
}
